### ISSUE TITLE
Update to 0.4.3

### ISSUE THREAD

**Issue by CosmicKetchup** [criscrafter/JMusicBot-Unraid#6]
Just a friendly notification that [v0.4.3](https://github.com/jagrosh/MusicBot/releases) was made available recently to address broken dependency issue affecting YouTube link playback.

Thanks for your efforts making this docker available and keeping it updated!

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExanV1Z3pueWY1bW9pZW5vNzNveG5lMzRlYXl1Z2x5MndleGZ5MHVncyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/zRKJFP8sOSL6Zu7I7j/giphy.gif)

**Comment by criscrafter** [comment]
I am in my nightshift rn, so I can't test the bot but I just pushed to Dockerhub. It should be updated.
You can either force update in Unraid under advanced settings or press Check for Updates on the bottom of the Page.

This is the first time I've pushed an update without testing, so hopefully all goes well. 😅

I mostly started this CA because I wanted it for myself. But it makes me very happy to see people use it.
You're Welcome and thank you :)

**Comment by DovarFalcone** [comment]
Thank you for your efforts. just updated and everything appears to be working well on initial test
